name: Switchres CI

on: [push, pull_request]

jobs:
  linux-build-standalone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libxrandr-dev libdrm-dev
    - name: make
      run: make
    - name: Prepare artifacts
      run: mkdir artifacts && cp switchres{,.ini} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres linux binary
        path: artifacts/
  
  linux-build-grid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libxrandr-dev libdrm-dev
    - name: make
      run: make grid
      with:
        name: switchres grid
        path: artifacts/

linux-build-lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libxrandr-dev libdrm-dev
    - name: make
      run: make libswitchres
    - name: Prepare artifacts
      run: mkdir artifacts && cp libswitchres.{so,a} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres linux lib
        path: artifacts/
